name: 'Setup'
description: 'Setup build'

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: sbt