name: Setup
description: Setup java

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - uses: sbt/setup-sbt@v1
