pull_request_rules:
  - name: automatic merge when author is dependabot
    conditions:
      - author=dependabot[bot]
      - check-success=unit-test
      - base=main
    actions:
      merge:
        method: rebase
  - name: automatic merge when author is scala-steward
    conditions:
      - author=scala-steward
      - check-success=unit-test
      - base=main
    actions:
      merge:
        method: rebase
