name: Scala Steward auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'mkuthan-scala-steward[bot]' }}

    steps:
      - name: Enable auto-merge for Scala Steward PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
