name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'sbt'

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Build and test
        run: sbt jacoco

      - name: Upload test coverage results
        uses: codecov/codecov-action@v3
