name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'sbt'

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Compile
        run: sbt compile

      - name: Unit test
        run: sbt jacoco

      - name: Integration test
        run: sbt it:jacoco

      - name: Upload test coverage results
        uses: codecov/codecov-action@v3
