name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'sbt'

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Unit test
        run: sbt jacoco

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Integration test
        run: sbt IntegrationTest/jacoco

      - name: Upload test coverage results
        uses: codecov/codecov-action@v3

  merge:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'scala-steward' }}
    needs:
      - build

    steps:
      - name: Merge
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
