name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Unit test
        run: sbt jacoco

#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v1
#        if: github.repository == 'mkuthan/stream-processing'
#        with:
#          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
#
#      - name: Integration test
#        if: github.repository == 'mkuthan/stream-processing'
#        run: sbt IntegrationTest/jacoco

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: '**/test-reports/*.xml'

      - name: Upload test coverage results
        uses: codecov/codecov-action@v3
