name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  scapegoat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt scapegoat
      - uses: actions/upload-artifact@v3
        with:
          name: scapegoat-report
          path: '**/scapegoat-report/*.html'

  test:
    runs-on: ubuntu-latest
    # disable for PRs from forks
    if: ${{ !github.event.pull_request.head.repo.fork }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: sbt jacoco
      - uses: codecov/codecov-action@v3

  required-checks:
    runs-on: ubuntu-latest
    needs: [scalafmt, scapegoat, test]
    steps:
      - run: exit 0
