name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: sbt jacoco
      - uses: codecov/codecov-action@v3
        with:
          flags: unit-tests

  integration-test:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'mkuthan'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: sbt IntegrationTest/jacoco
      - uses: codecov/codecov-action@v3
        with:
          flags: integration-tests
