name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  test:
    runs-on: ubuntu-latest
    # disable for PRs from forks
    if: ${{ !github.event.pull_request.head.repo.fork }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: sbt jacoco
      - uses: codecov/codecov-action@v3

  required-checks:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: exit 0
