name: CI

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt scalafmtCheckAll

  scapegoat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt scapegoat
      - uses: actions/upload-artifact@v3
        with:
          name: scapegoat-report
          path: "**/scapegoat-report/*.html"

  scalafix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt "scalafixAll --check"

  tf-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dflook/terraform-validate@v1
        with:
          path: toll-infrastructure

  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dflook/terraform-fmt-check@v1
        with:
          path: toll-infrastructure

  test:
    runs-on: ubuntu-latest
    needs: [scalafmt, scapegoat, scalafix, tf-validate, tf-fmt]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - run: sbt jacoco
      - uses: codecov/codecov-action@v3
