name: Deploy

on:
  workflow_dispatch: ~
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: sbt tollApplication/assembly
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - uses: dflook/terraform-apply@v1
        with:
          path: toll-infrastructure
      # TODO: fix IAM and deploy flex templates
      # - uses: "google-github-actions/setup-gcloud@v1"
      # - run: ./deploy-batch.sh
      #   working-directory: toll-application
      # - run: ./deploy-streaming.sh
      #   working-directory: toll-application

      # TODO: run streaming job
      # TODO: deploy DAG for batch job
